# Generated by Django 5.2.7 on 2025-12-04 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen_file_rpg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('senha', models.CharField(blank=True, help_text='Opcional: Senha para entrar', max_length=20, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_mestradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_gen_file_rpg.fichapersonagem')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='app_gen_file_rpg.mesa')),
            ],
            options={
                'unique_together': {('mesa', 'jogador')},
            },
        ),
    ]
