# Generated by Django 5.2.7 on 2025-12-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gen_file_rpg', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='senha',
        ),
    ]
